name: Aggregated Lighthouse Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: lhci auto

      - name: List current directory contents
        run: ls -l
        
      # Upload Lighthouse Reports as Artifacts
      - name: Upload Lighthouse Reports as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: ./lhci_reports
