name: Aggregated Lighthouse Tests

on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Lighthouse CI
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      # Run Lighthouse CI multiple times (e.g., 3 runs)
      - name: Run Lighthouse CI multiple times
        run: |
          ls
          npx -p @lhci/cli lhci collect --url https://example.com -n 3 --outputDir ./lhci_reports

      # Install dependencies and run the process-reports.js script
      - name: Process Lighthouse reports for 95th percentile
        run: |
          ls
          # Install dependencies to process the reports
          npm install fs
          # Run the custom JavaScript file that processes the reports
          node ./process-reports.js

      # Upload Lighthouse Reports as Artifacts
      - name: Upload Lighthouse Reports as Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: ./lhci_reports
