name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Create Lighthouse Config
        run: |
          echo '{
            "ci": {
              "assert": {
                "assertions": {
                  "first-contentful-paint": ["error", {"maxScore": 1800}],
                  "largest-contentful-paint": ["error", {"maxScore": 2500}],
                  "interactive-to-next-paint": ["error", {"maxScore": 200}],
                  "cumulative-layout-shift": ["error", {"maxScore": 0.1}]
                }
              }
            }
          }' > lhci-config.json

      - name: Run Lighthouse for Multiple URLs
        run: |
          mkdir -p lhci_reports
          lhci autorun --collect.url=https://example.cypress.io/ --upload.target=filesystem --upload.outputDir=./lhci_reports/homepage
          # lhci autorun --collect.url=https://example.cypress.io/commands/querying --upload.target=filesystem --upload.outputDir=./lhci_reports/querying
          # lhci autorun --collect.url=https://example.cypress.io/utilities --upload.target=filesystem --upload.outputDir=./lhci_reports/utilities

      - name: Run Lighthouse CI with Thresholds
        run: |
          # Run assertions based on the config file
          lhci assert --config=lhci-config.json
          
      - name: Upload Lighthouse Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: ./lhci_reports
