name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: lhci autorun

      - name: Run Lighthouse Assertions
        run: |
          lhci assert || echo "⚠️ Lighthouse scores are below the set thresholds! Check the report for details."

      - name: Upload Lighthouse Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: ./lhci_reports
